-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mer. 12 avr. 2023 à 10:30
-- Version du serveur : 5.7.36
-- Version de PHP : 7.4.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `news_db`
--

-- --------------------------------------------------------

--
-- Structure de la table `news`
--

DROP TABLE IF EXISTS `news`;
CREATE TABLE IF NOT EXISTS `news` (
  `id` smallint(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `auteur` varchar(30) NOT NULL,
  `titre` varchar(100) NOT NULL,
  `contenu` text NOT NULL,
  `dateAjout` datetime NOT NULL,
  `dateModif` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `news`
--

INSERT INTO `news` (`id`, `auteur`, `titre`, `contenu`, `dateAjout`, `dateModif`) VALUES
(8, 'L\'EQUIPE', 'L\'inter prend une option en allant battre Benfica', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque et facilis optio, eos repudiandae, omnis corporis recusandae voluptatem quas accusantium earum iusto quam sunt ex inventore quae placeat! Libero, saepe?\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Alias inventore maiores, laudantium nihil aut quo iste quis. Pariatur magni nisi eveniet ut adipisci maxime itaque, rerum ea hic voluptatibus atque?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Quas consequatur quod quibusdam, qui iure reprehenderit tenetur vero impedit praesentium quaerat, pariatur tempore corrupti nobis, expedita esse sit assumenda beatae temporibus.\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Neque, debitis voluptatibus temporibus consequuntur suscipit at, eius quod optio dicta porro quae. Voluptas officia eligendi mollitia omnis earum nam molestiae numquam?\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla quia et quisquam velit, voluptas corporis impedit? Eum rerum earum placeat unde obcaecati, quaerat explicabo nihil commodi. Odit vitae provident maxime.\r\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi, inventore aliquam ratione asperiores ipsa vero nesciunt, repellat ex possimus, iure est. Suscipit debitis delectus dolor qui, cupiditate quam ab magnam.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione quia iste, unde maiores mollitia cumque sit animi a. Autem placeat, quod cupiditate animi quam tempora sapiente aliquid recusandae perspiciatis voluptas.\r\n\r\n', '2023-04-12 00:00:24', '2023-04-12 00:00:24'),
(9, 'L\'EQUIPE', 'City dompte le Bayern et pose un pied en demies', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque et facilis optio, eos repudiandae, omnis corporis recusandae voluptatem quas accusantium earum iusto quam sunt ex inventore quae placeat! Libero, saepe?\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Alias inventore maiores, laudantium nihil aut quo iste quis. Pariatur magni nisi eveniet ut adipisci maxime itaque, rerum ea hic voluptatibus atque?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Quas consequatur quod quibusdam, qui iure reprehenderit tenetur vero impedit praesentium quaerat, pariatur tempore corrupti nobis, expedita esse sit assumenda beatae temporibus.\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Neque, debitis voluptatibus temporibus consequuntur suscipit at, eius quod optio dicta porro quae. Voluptas officia eligendi mollitia omnis earum nam molestiae numquam?\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla quia et quisquam velit, voluptas corporis impedit? Eum rerum earum placeat unde obcaecati, quaerat explicabo nihil commodi. Odit vitae provident maxime.\r\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi, inventore aliquam ratione asperiores ipsa vero nesciunt, repellat ex possimus, iure est. Suscipit debitis delectus dolor qui, cupiditate quam ab magnam.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione quia iste, unde maiores mollitia cumque sit animi a. Autem placeat, quod cupiditate animi quam tempora sapiente aliquid recusandae perspiciatis voluptas.\r\n', '2023-04-12 00:02:38', '2023-04-12 00:02:38'),
(10, 'Football.fr', 'Le coup de canon de Rodri face Ã  Sommer', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque et facilis optio, eos repudiandae, omnis corporis recusandae voluptatem quas accusantium earum iusto quam sunt ex inventore quae placeat! Libero, saepe?\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Alias inventore maiores, laudantium nihil aut quo iste quis. Pariatur magni nisi eveniet ut adipisci maxime itaque, rerum ea hic voluptatibus atque?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Quas consequatur quod quibusdam, qui iure reprehenderit tenetur vero impedit praesentium quaerat, pariatur tempore corrupti nobis, expedita esse sit assumenda beatae temporibus.\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Neque, debitis voluptatibus temporibus consequuntur suscipit at, eius quod optio dicta porro quae. Voluptas officia eligendi mollitia omnis earum nam molestiae numquam?\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla quia et quisquam velit, voluptas corporis impedit? Eum rerum earum placeat unde obcaecati, quaerat explicabo nihil commodi. Odit vitae provident maxime.\r\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi, inventore aliquam ratione asperiores ipsa vero nesciunt, repellat ex possimus, iure est. Suscipit debitis delectus dolor qui, cupiditate quam ab magnam.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione quia iste, unde maiores mollitia cumque sit animi a. Autem placeat, quod cupiditate animi quam tempora sapiente aliquid recusandae perspiciatis voluptas.\r\n', '2023-04-12 00:04:44', '2023-04-12 00:04:44'),
(11, 'bein Sport', 'LÃ©o Messi, meilleur buteur d\'Europe !', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque et facilis optio, eos repudiandae, omnis corporis recusandae voluptatem quas accusantium earum iusto quam sunt ex inventore quae placeat! Libero, saepe?\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Alias inventore maiores, laudantium nihil aut quo iste quis. Pariatur magni nisi eveniet ut adipisci maxime itaque, rerum ea hic voluptatibus atque?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Quas consequatur quod quibusdam, qui iure reprehenderit tenetur vero impedit praesentium quaerat, pariatur tempore corrupti nobis, expedita esse sit assumenda beatae temporibus.\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Neque, debitis voluptatibus temporibus consequuntur suscipit at, eius quod optio dicta porro quae. Voluptas officia eligendi mollitia omnis earum nam molestiae numquam?\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla quia et quisquam velit, voluptas corporis impedit? Eum rerum earum placeat unde obcaecati, quaerat explicabo nihil commodi. Odit vitae provident maxime.\r\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi, inventore aliquam ratione asperiores ipsa vero nesciunt, repellat ex possimus, iure est. Suscipit debitis delectus dolor qui, cupiditate quam ab magnam.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione quia iste, unde maiores mollitia cumque sit animi a. Autem placeat, quod cupiditate animi quam tempora sapiente aliquid recusandae perspiciatis voluptas.\r\n', '2023-04-12 00:06:38', '2023-04-12 00:11:26'),
(12, 'L\'EQUIPE', 'LE BARCA FONCE VERS LE TITRE !', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque et facilis optio, eos repudiandae, omnis corporis recusandae voluptatem quas accusantium earum iusto quam sunt ex inventore quae placeat! Libero, saepe?\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Alias inventore maiores, laudantium nihil aut quo iste quis. Pariatur magni nisi eveniet ut adipisci maxime itaque, rerum ea hic voluptatibus atque?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Quas consequatur quod quibusdam, qui iure reprehenderit tenetur vero impedit praesentium quaerat, pariatur tempore corrupti nobis, expedita esse sit assumenda beatae temporibus.\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Neque, debitis voluptatibus temporibus consequuntur suscipit at, eius quod optio dicta porro quae. Voluptas officia eligendi mollitia omnis earum nam molestiae numquam?\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla quia et quisquam velit, voluptas corporis impedit? Eum rerum earum placeat unde obcaecati, quaerat explicabo nihil commodi. Odit vitae provident maxime.\r\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi, inventore aliquam ratione asperiores ipsa vero nesciunt, repellat ex possimus, iure est. Suscipit debitis delectus dolor qui, cupiditate quam ab magnam.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione quia iste, unde maiores mollitia cumque sit animi a. Autem placeat, quod cupiditate animi quam tempora sapiente aliquid recusandae perspiciatis voluptas.\r\n', '2023-04-12 00:14:36', '2023-04-12 00:16:18'),
(13, 'Football.fr', 'Le Real de Madrid s\'incline 3-2 face Ã  Villareal !', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque et facilis optio, eos repudiandae, omnis corporis recusandae voluptatem quas accusantium earum iusto quam sunt ex inventore quae placeat! Libero, saepe?\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Alias inventore maiores, laudantium nihil aut quo iste quis. Pariatur magni nisi eveniet ut adipisci maxime itaque, rerum ea hic voluptatibus atque?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Quas consequatur quod quibusdam, qui iure reprehenderit tenetur vero impedit praesentium quaerat, pariatur tempore corrupti nobis, expedita esse sit assumenda beatae temporibus.\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Neque, debitis voluptatibus temporibus consequuntur suscipit at, eius quod optio dicta porro quae. Voluptas officia eligendi mollitia omnis earum nam molestiae numquam?\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla quia et quisquam velit, voluptas corporis impedit? Eum rerum earum placeat unde obcaecati, quaerat explicabo nihil commodi. Odit vitae provident maxime.\r\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi, inventore aliquam ratione asperiores ipsa vero nesciunt, repellat ex possimus, iure est. Suscipit debitis delectus dolor qui, cupiditate quam ab magnam.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione quia iste, unde maiores mollitia cumque sit animi a. Autem placeat, quod cupiditate animi quam tempora sapiente aliquid recusandae perspiciatis voluptas.\r\n', '2023-04-12 00:19:52', '2023-04-12 00:21:23'),
(14, 'bein Sports', 'CITY HUMILIE LE BAYERN 3 - 0 !', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque et facilis optio, eos repudiandae, omnis corporis recusandae voluptatem quas accusantium earum iusto quam sunt ex inventore quae placeat! Libero, saepe?\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Alias inventore maiores, laudantium nihil aut quo iste quis. Pariatur magni nisi eveniet ut adipisci maxime itaque, rerum ea hic voluptatibus atque?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Quas consequatur quod quibusdam, qui iure reprehenderit tenetur vero impedit praesentium quaerat, pariatur tempore corrupti nobis, expedita esse sit assumenda beatae temporibus.\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Neque, debitis voluptatibus temporibus consequuntur suscipit at, eius quod optio dicta porro quae. Voluptas officia eligendi mollitia omnis earum nam molestiae numquam?\r\nLorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla quia et quisquam velit, voluptas corporis impedit? Eum rerum earum placeat unde obcaecati, quaerat explicabo nihil commodi. Odit vitae provident maxime.\r\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi, inventore aliquam ratione asperiores ipsa vero nesciunt, repellat ex possimus, iure est. Suscipit debitis delectus dolor qui, cupiditate quam ab magnam.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione quia iste, unde maiores mollitia cumque sit animi a. Autem placeat, quod cupiditate animi quam tempora sapiente aliquid recusandae perspiciatis voluptas.\r\n', '2023-04-12 00:23:41', '2023-04-12 08:21:08');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
